### ISSUE TITLE
Some sub weapon costs are wrong.

### ISSUE THREAD

**Issue by filipkoperwas** [DeviPotato/splat2-calc#1]
Sprinkler should cost 80 instead of 90, and splash wall should cost 60 instead of 90.

Source is Heddy's sub saver chart available at this link: https://splatoonwiki.org/wiki/File:S2_Ink_Saver_Sub_Chart.png

**Comment by DeviPotato** [comment]
Thanks for the report, I just pushed the fix. That's what I get for doing data entry on no sleep, I guess.
