### ISSUE TITLE
Missing boots: Angry Rain Boots

### ISSUE THREAD

**Issue by Freezinater** [DeviPotato/splat2-calc#13]
I'm trying to check out the stats on what I currently have, and I am currently using Angry Rain Boots obtained from Salmon Run. However, I can't seem to find them after mousing over each and every set of boots.

**Comment by DeviPotato** [comment]
Missing gear has been addressed in commit 1989a7fe0e7f35769e074f877de2043b94099acc. Thank you for your patience.
