### ISSUE TITLE
Wrong Italian Flag in Language Selector

### ISSUE THREAD

**Issue by marcolago** [DeviPotato/splat2-calc#19]
In the Italian flag, the white stripe is clean, without any symbol, and the green stripe is slightly lighter.
The flag used now is the Mexican one.

**Comment by DeviPotato** [comment]
The language selector doesn't include the Italian flag at all - I have been using the flags to denote region-specific localizations/dialects only (two versions of Spanish/French, Cantonese Chinese).

![image](https://user-images.githubusercontent.com/7655054/38666853-d50ea924-3df4-11e8-9531-b38677b2439b.png)

The Mexican flag you see is for the Mexican localization. :)

If they are rendering in a way that they appear mis-matched, then I can try to fiddle with it and make it more clear.

**Comment by marcolago** [comment]
Ops, sorry!
I saw the flags only in mobile mode and the layout is a little messed up with the Mexican flag under the “Italiano” word.

Maybe a cache issue.
I’ve tried right now and everything is fine.

**Comment by DeviPotato** [comment]
No problem! I'll still touch up this page a bit so it doesn't get quite so cluttered on mobile.
