### ISSUE TITLE
Incorrect "Ink Consumption (Sub)" tooltip

### ISSUE THREAD

**Issue by e-foley** [DeviPotato/splat2-calc#20]
![sub_reduction](https://user-images.githubusercontent.com/6338134/39091617-31b2ba44-45ac-11e8-8078-95bfd8ef57a2.png)

Tooltip shows 0.2% reduction when it should really be about 22%.  My guess is that a factor of 100 is missing.

**Comment by DeviPotato** [comment]
This is resolved in the new version being deployed this week.
