### ISSUE TITLE
Inconsistent special cost rounding between Weapon box and Special Charge Speed tooltip

### ISSUE THREAD

**Issue by e-foley** [DeviPotato/splat2-calc#21]
![special_cost](https://user-images.githubusercontent.com/6338134/39091704-5fd160a8-45af-11e8-8543-df32a60ce341.png)

As you can see in the image, the Weapon box shows 122p whereas the tooltip shows 123p.  This is a super tiny detail.

**Comment by DeviPotato** [comment]
This should be resolved in an update being deployed this week.

Thank you for your patience.
