### ISSUE TITLE
What about an update to Splatoon 2 version 3.2.x?

### ISSUE THREAD

**Issue by acidghost** [DeviPotato/splat2-calc#25]
There are missing weapons and some changes to old weapons. @DeviPotato, could you update to the latest splatoon version?

**Comment by solairemomo** [comment]
this is still an ongoing issue, so im just posting here to confirm instead of opening a whole new issue thread. the new gear and weapons are still missing from loadout.ink as of today's date.

**Comment by Hario337** [comment]
Does anyone know why it's taking so long?

**Comment by DeviPotato** [comment]
This is resolved in an update being deployed this week.

Thank you for your patience.
