### ISSUE TITLE
Power up main?

### ISSUE THREAD

**Issue by TheRealNaaka** [DeviPotato/splat2-calc#26]
I don't see power up main as an ability to pick from in the calculator, kinda ruins the whole point of using it for my purposes.

**Comment by slushiegoose** [comment]
This is heavily outdated - I'm workin on a fork rn

**Comment by DeviPotato** [comment]
This is resolved in an update being deployed this week.

Thank you for your patience.

**Comment by karlingen** [comment]
@DeviPotato Can't see the changes @ https://loadout.ink/
