### ISSUE TITLE
Missing weapons

### ISSUE THREAD

**Issue by LeSpirou** [DeviPotato/splat2-calc#31]
Hi, as far as I know there are missing: Aerospray PG, Squeezer Foil (both shooter).
Aerospray PG:
Same stats as Aerospray MG but having burst bombs as sub weapon and booyah bomb as special.
Squeezer Foil:
Same stats as Squeezer but having splat bombs as sub weapon and bubble blower as special.

**Comment by LeSpirou** [comment]
Neo Splash-O-Matic:
Same stats as Splash-O-Matic but having burst bombs as sub weapon and suction bomb rush special.

**Comment by LightClover3337** [comment]
theres a lot of things missing
